# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
orbs:
  slack: circleci/slack@4.1
  aws-cli: circleci/aws-cli@1.4.0  
# Orchestrate or schedule a set of jobs
jobs:
  lint:
    docker:
      - image: python:3.7.3-stretch
    steps:
      - checkout
      - run:
          name: Make install
          command: |
            # Your code here
            make install
      - run:
          name: Lint dockerfile and html
          command: |
            # Your code here
            make lint

      - slack/notify:
          event: fail
          template: basic_fail_1

workflows:
  # Name the workflow "welcome"
  welcome:
    # Run the welcome/run job in its own container
    jobs:
      - lint
